[phases.setup]
nixPkgs = [
  "nodejs_18",
  "libnss3",
  "libatk-1.0",
  "libatk-bridge2.0",
  "libcups2",
  "libgbm1",
  "libasound2",
  "libpangocairo-1.0",
  "libxss1",
  "libgtk-3.0",
  "libxshmfence1",
  "libglu1"
]
