[phases.setup]
nixPkgs = [
  "nodejs_18",
  "nss",
  "atk",
  "atkmm",
  "cups",
  "libdrm",
  "gtk3",
  "alsa-lib",
  "libxshmfence",
  "libxss1",
  "libxtst",
  "libgbm1",
  "libgl1",
  "libnss3",
  "libasound2",
  "libatk-1.0",
  "libatk-bridge2.0"
]
