[phases.setup]
nixPkgs = [
  "nodejs_18",
  "nss",
  "libxss1",
  "libgconf-2-4",
  "libasound2",
  "libatk-1.0",
  "libatk-bridge2.0",
  "libcups2",
  "libdrm",
  "libgbm1",
  "libglu1",
  "libgtk-3.0",
  "libxshmfence",
  "libxcomposite",
  "libxdamage",
  "libxrandr",
  "libxtst",
  "libuuid"
]
