[phases.setup]
nixPkgs = [
  "nodejs_18",
  "nss",
  "atk",
  "atkmm",
  "cups",
  "libdrm",
  "gtk3",
  "pango",
  "alsa-lib",
  "libxshmfence",
  "libxcomposite",
  "libxdamage",
  "libxrandr",
  "libxss",
  "libxtst",
  "mesa",
  "glib",
  "expat",
  "libuuid",
  "libusb1"
]
